### PR TITLE
test: regenerate test certificates

### PR DESCRIPTION
**Pull request by richlowe**
This regenerates the TLS certificates used during testing, allowing the test suite to reflect reality.
Done via `src/tests/ro_data/signing_certs/generate_certs.py`

### CODE REVIEW

**Comment by Toasterson** [comment]
Should we not rather delete the certs and generate them during testing. This is a huge diff with only cert changes.

**Review by Toasterson — CHANGES_REQUESTED** [review]
I think we should not have the certs commited here, as we would need to regerneate them way too often, and that creates friction with omnios-pkg and solaris-pkg which we don't want

**Comment by richlowe** [comment]
I mean, everyone has test certs committed.  All deleting them does is also create a huge diff?

**Comment by richlowe** [comment]
The more interesting problem I'm having is the test results aren't 100% stable for me regardless, unfortunately, so I'll keep plugging away at this and also that

**Comment by richlowe** [comment]
I pushed a branch to generate them when we run make install, redirecting the output because I cannot get openssl to shut up any other way.  @citrus-it does this seem good to you too? I see you've had to change package sizes in some tests when regenerating before, but I haven't had to do that.  I _do_ however, have all kids of problems with running the tests in parallel right now.

**Comment by Toasterson** [comment]
It's not about the size of this diff. One diff is going to be huge if we delete the certs or update them, what bothers me, is that there are produced test certs committed in the first place. I don't think they need to be committed at all. I usually treat these kinds of files as ephemeral artifacts in .gitignore and their generation is simply part of the testing proces. Is there any reason we need them in this repo?

**Comment by Toasterson** [comment]
Ah, I see you now deleted them out :)

**Comment by richlowe** [comment]
The "do we need them in this repo" is the bit I was asking Andy about.  I can't see a reason why, but updates Andy has made in the past suggest that some of the tests depend on some aspects of the certs.

**Comment by richlowe** [comment]
I took this back to how it was initially, per conversation with @Toasterson and @citrus-it

**Review by Toasterson — APPROVED** [review]
LGTM

**Pull request merged**
