### PR TITLE
Omnios merge

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
This also requires changes to oi-userland - its build scripts use python 2.7 and pkg modules. 
Have to switch them to Python3.5.

**Comment by pyhalov** [comment]
@citrus-it - note https://github.com/OpenIndiana/pkg5/pull/65/commits/31430562b31e4d04c259cbedadc627db25c839ab
Without it cdrom mounting is broken.

**Comment by pyhalov** [comment]
We have pkgdepend issue on slim_source:
````
Traceback (most recent call last):
  File "/usr/bin/pkgdepend", line 605, in <module>
    __ret = main_func()
  File "/usr/bin/pkgdepend", line 584, in main_func
    return resolve(pargs, img_dir)
  File "/usr/bin/pkgdepend", line 342, in resolve
    system_patterns, prune_attrs=not verbose)
  File "/usr/lib/python3.5/vendor-packages/pkg/publish/dependencies.py", line 1753, in resolve_deps
    pfmri, mfst, use_template=True)
  File "/usr/lib/python3.5/vendor-packages/pkg/publish/dependencies.py", line 1637, in add_fmri_path_mapping
    for f in mfst.gen_actions_by_type("file"):
  File "/usr/lib/python3.5/vendor-packages/pkg/manifest.py", line 1834, in gen_actions_by_type
    for l in f:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1831: ordinal not in range(128)
```

**Comment by Mno-hime** [comment]
Python 3 `pkg verify` shows a bit odd output for wrong modes:
```
pkg://openindiana.org/desktop/mate/control-center                        ERROR
        file: usr/share/mime/application/x-mate-theme-package.xml
                ERROR: Group: 'root (0)' should be 'bin (2)'
                ERROR: Mode: 0o644 should be 0o444
```
Python 2 `pkg`:
```
pkg://openindiana.org/desktop/mate/control-center                        ERROR
        file: usr/share/mime/application/x-mate-theme-package.xml
                ERROR: Group: 'root (0)' should be 'bin (2)'
                ERROR: Mode: 0644 should be 0444
```

**Comment by pyhalov** [comment]
Hm.. This is expected in some way. Likely missed some upstream fix

**Comment by pyhalov** [comment]
So far, UnicodeDecodeError is annoyng. I wonder if pkg should force en_US.UTF-8 locale if it's set to C...

**Comment by Mno-hime** [comment]
```
PATH=/export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/src/pkg/../../proto/root_i386/usr/bin:/usr/sbin:/usr/bin  PYTHONPATH=/export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/src/pkg/../../proto/root_i386/usr/lib/python3.5/vendor-packages python3.5 /export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/src/pkg/../../proto/root_i386/usr/bin//pkgrepo create /export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/packages/i386/repo
Traceback (most recent call last):
  File "/export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/src/pkg/../../proto/root_i386/usr/bin//pkgrepo", line 73, in <module>
    from prettytable import PrettyTable
ImportError: No module named 'prettytable'
*** Error code 1
make: Fatal error: Command failed for target `/export/home/newman/ws/oi-userland/components/openindiana/pkg/pkg/packages/i386/repo'
```
`REQUIRED_PACKAGES += library/python/prettytable-35` is missing in the `Makefile`.

**Comment by Mno-hime** [comment]
Slightly better if it had the leading zero as it used to be with Python 2 `pkg`:
```
root@toshiba:~# chmod 1777 /usr/bin/ls 
root@toshiba:~# pkg verify SUNWcs
PACKAGE                                                                 STATUS
pkg://openindiana.org/SUNWcs                                             ERROR
        file: usr/bin/ls
                ERROR: Mode: 1777 should be 555
```

**Comment by pyhalov** [comment]
Zero which you had with Py2 was in fact an accident - you would have 0777, but also 01777, it was not for leading zero, but for python octal integer representation.

**Comment by pyhalov** [comment]
If pkg just forces en_US.UTF-8 locale if it's set to C, something is wrong with date formatting in pkgdepot output. Need to look at it further. 
So far adding fixes for pkgdepend failures. Need to run IPS tests after this.

**Comment by citrus-it** [comment]
> @citrus-it - note [3143056](https://github.com/OpenIndiana/pkg5/commit/31430562b31e4d04c259cbedadc627db25c839ab)
> Without it cdrom mounting is broken.

We have this as bc436079a95d4e82fc6fb863733d6d3a4838a5e7

**Pull request merged**
