### PR TITLE
Update sections in moved man pages per IPD4

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by Toasterson** [comment]
@richlowe @citrus-it does anything like this exist in the omnios pkg? Or something that could cause merge conflicts?

@mtelka we are currently merging in omnios pkg changes into openindiana pkg I would like not to influence that process.

**Comment by citrus-it** [comment]
> @richlowe @citrus-it does anything like this exist in the omnios pkg? Or something that could cause merge conflicts?

The man pages in the OmniOS fork have been completely converted over to mdoc(7), and also have extra pieces from changes you don't have in OI yet. I certainly wouldn't block this because of the ongoing merge.

**Comment by Toasterson** [comment]
Ok, thanks for the insights! Will merge now.

**Comment by AndWac** [comment]
pkg doesn't publish anymore:
byte-compiling /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/proto/root_i386/usr/lib/python3.9/vendor-packages/pkg/server/transaction.py to transactionrunning install_data
copying po/pkg.pot -> /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/proto/root_i386/usr/share/locale/__LOCALE__/LC_MESSAGES
running install_egg_info
Removing /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/proto/root_i386/usr/lib/python3.9/vendor-packages/pkg-0.1-py3.9.egg-info
Writing /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/proto/root_i386/usr/lib/python3.9/vendor-packages/pkg-0.1-py3.9.egg-info
PATH=/jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/src/pkg/../../proto/root_i386/usr/bin:/usr/sbin:/usr/bin  PYTHONPATH=/jenkins/jobs/oi-userland/worksna/pkg/pkg/src/pkg/../../proto/root_i386/usr/lib/python3.9/vendor-packages /usr/bin/python3.9 /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/src/pkg/../n//pkgfmt -c manifests/*.p5m
pkgfmt: error: manifests/developer:opensolaris:pkg5.p5m is not in pkgfmt form; run pkgfmt on file without -c or -d to reformat manifest in place
pkgfmt: error: manifests/package:pkg:depot.p5m is not in pkgfmt form; run pkgfmt on file without -c or -d to reformat manifest in place
pkgfmt: error: manifests/package:pkg:system-repository.p5m is not in pkgfmt form; run pkgfmt on file without -c or -d to reformat manifest in place
*** Error code 1
make: Fatal error: Command failed for target `pkgfmt'
Current working directory /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/pkg/src/pkg
gmake: *** [Makefile:54: /jenkins/jobs/oi-userland/workspace/components/openindiana/pkg/build/i386/.built] Error 1

**Comment by mtelka** [comment]
> pkg doesn't publish anymore:

Yep.  The root cause is here: https://github.com/OpenIndiana/pkg5/pull/113

**Comment by Toasterson** [comment]
Fixed on #115 thanks @mtelka for the pointer

**Pull request merged**
