### PR TITLE
Remove dependency on m2crypto

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by Mno-hime** [comment]
Is there some documentation on how to get all the deps, build and install from sources correctly?

**Comment by pyhalov** [comment]
I usually just use https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components/openindiana/pkg component to rebuild pkg. After that you can do something like ```python2.7 run.py -v -a /var/tmp/failed_ips_tests``` in oi-userland/components/openindiana/pkg/src/tests to run test suite.

**Comment by citrus-it** [comment]
I usually do this in the checkout:

```
cd src
CC=gcc make install
cd tests
pfexec python2.7 run.py -j 8 ...
```

The make install delivers everything to proto/ at the top and that's where tests run from.
The `-j 8` runs it with 8 parallel threads

**Comment by pyhalov** [comment]
```
BASELINE MISMATCH: The following results didn't match the baseline.
----------------------------------------------------------------------
cli.t_pkgdep.py TestPkgdepBasics.test_PEP_3149: fail
cli.t_pkgdep.py TestPkgdepBasics.test_bug_11805: error
cli.t_pkgdep.py TestPkgdepBasics.test_bug_13059: fail
cli.t_pkgdep.py TestPkgdepBasics.test_output: error
cli.t_pkgdep.py TestPkgdepBasics.test_python_combinations: error
cli.t_pkg_info.py TestPkgInfoBasics.test_ranked: fail
cli.t_pkg_linked.py TestPkgLinkedRecurse.test_recursive_variant: fail
cli.t_pkg_linked.py TestPkgLinkedScale.test_li_scale: fail
----------------------------------------------------------------------
```
cli.t_pkg_linked.py TestPkgLinkedScale.test_li_scale: fail is new one, but it fails due to 'too many open files' error, so I see no regressions here.

**Pull request merged**
