### PR TITLE
12742 pkg server tracebacks with TypeError: string argument expected, got 'bytes'

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
@citrus-it Have you seen this?

**Comment by citrus-it** [comment]
> @citrus-it Have you seen this?

No - a licence with UTF-8 in it somewhere?

**Comment by pyhalov** [comment]
No. It doesn't matter. I wonder how can it work in current form. gunzip_from_stream() expect bytes stream/file, but gets string one.

**Comment by pyhalov** [comment]
It seems I haven't broken test suite with this change.
There are, however, some lint test errors:
```
======================================================================
BASELINE MISMATCH: The following results didn't match the baseline.
----------------------------------------------------------------------
api.t_pkglint.py TestLintEngine.test_lint_checks: fail
api.t_pkglint.py TestLintEngineDepot.test_broken_legacy_rename: fail
api.t_pkglint.py TestLintEngineDepot.test_empty_lint_repo: fail
api.t_pkglint.py TestLintEngineDepot.test_lint_repo_basics: fail
======================================================================
```

**Pull request merged**
