### PR TITLE
remove obsolete/unused components

### PR DESCRIPTION
**Pull request by richlowe**
This removes the dangling trusted desktop directories that should have been removed by 40ff100d, and the RAD component that was never exactly packaged and can't ever work because RAD was never available to us.

`make test` is clean, it's not clear what else I could do to test it.  @citrus-it could you look at this too? I don't think y'all removed the RAD bits yet.

### CODE REVIEW

**Comment by richlowe** [comment]
I should have added, this is part of the work to get the build actually clean so when I try to land the 3.9 stuff we can compare apples to apples.  There are a large handful of further changes to make pkglint and protocmp actually clean when you build packages.

**Review by Toasterson — APPROVED** [review]
Looks good from my side Let me know when you are ready to merge.

**Comment by richlowe** [comment]
This bit can go in when @citrus-it is happy with it, I think.

**Review by citrus-it — APPROVED** [review]

**Comment by citrus-it** [comment]
> This bit can go in when @citrus-it is happy with it, I think.

Looks good to me. I'll pull the same commits over to the OmniOS pkg5, thanks.

**Pull request merged**
