### PR TITLE
Remove dependency on python 3.5

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Review by AndWac — APPROVED** [review]

**Comment by Toasterson** [comment]
I am on the run now but the only thing that usually sticks out with pkg is if pkgfmt has not been run over the manifest. Otherwise LGTM, CC: @citrus-it and @richlowe so they also know things are moving.

**Review by Toasterson — APPROVED** [review]

**Comment by richlowe** [comment]
I was hoping this would land after I switch the default in illumos, but nobody is looking at my RTI yet.  If you go first, you'll need a headsup to the illumos lists, etc.

**Comment by mtelka** [comment]
> If you go first, you'll need a headsup to the illumos lists, etc.

Why?

**Comment by richlowe** [comment]
Because python 3.5 is still the default in illumos until I land my change to make it 3.9, so the illumos validate_pkg will try to use python 3.5 pkg5 python modules, which after your change won't exist.

**Comment by richlowe** [comment]
Actually, Dan just approved by RTI (illumos #14847), so if you wait a couple hours I should have landed and sent my own headsup, which you can reply to and move the line about OI.

**Comment by mtelka** [comment]
> Because python 3.5 is still the default in illumos until I land my change to make it 3.9, so the illumos validate_pkg will try to use python 3.5 pkg5 python modules, which after your change won't exist.

Thanks for explanation.  Makes sense.  @AndWac, please wait with the merge until illumos#14847 is pushed.

**Comment by mtelka** [comment]
> Actually, Dan just approved by RTI (illumos #14847), so if you wait a couple hours I should have landed and sent my own headsup, which you can reply to and move the line about OI.

Yes.  After illumos#14847 is pushed and this PR is merged developers will no longer needed to set `export BUIDPY3b=''` in their env files while building illumos-gate.  But, OTOH, it should be harmless if it is left set (unless OI obsoletes `runtime/python-35`, which won't happen soon anyway).

**Pull request merged**
