### PR TITLE
Follow package renames and convert egg-info file to directory

### PR DESCRIPTION
**Pull request by mtelka**

### CODE REVIEW

**Comment by Toasterson** [comment]
@richlowe @citrus-it Pinging you both as you may want that aswell. Otherwise LGTM

**Review by klausz65 — APPROVED** [review]
Correctly published again on SPARC

**Comment by mtelka** [comment]
The conversion of egg-info file to directory is needed because new Python tools create by default egg-info as a directory now.

OTOH, I just found that the egg-info (either file or directory) causes some confusion for other Python projects.  With the egg-info the 'pkg' package is visible by tools like pip, but test suite for importlib_metadata project does not expect that and testing fails there.  Possible solution for this is a removal of egg-info to make the 'pkg' package a hidden package.  If we will decide to do that we will do it using transforms in the oi-userland repo.

**Comment by citrus-it** [comment]
> @richlowe @citrus-it Pinging you both as you may want that aswell. Otherwise LGTM

Thanks for the ping. It looks like this done in the OmniOS pkg as part of https://github.com/omniosorg/pkg5/commit/a1cf64480a9fec64c61e735bfd3028fee38c896f

**Pull request merged**
